### ISSUE TITLE
Issue with loading template in desktop app

### ISSUE THREAD

**Issue by Stegnerd** [sgosiaco/wails-template-quasar-ts#1]
Environment:
Macos Ventura 13.4.1
go version: 1.18
wails version: 2.5.1

repro steps:
1. ran the command `wails init -n myappname -t https://github.com/sgosiaco/wails-template-quasar-ts.git`
2. cd into and run wails dev ( I made 0 changes)

App looks like this and I opened the debug console so it could be viewed as well: 
https://github.com/sgosiaco/wails-template-quasar-ts/assets/12737758/012ae6ec-3a21-4510-b7b6-ec9997a05438

It loads just fine if I only go to this link in a browser: `http://localhost:5173/#/` . It also runs just fine as a dektop application if I run the `wails build` command and run that executable

**Comment by sgosiaco** [comment]
@Stegnerd I just pushed a new version v1.2.0 if you can try that out.
Looks like the changes made in v2.5.0 regarding this:
> wails dev now uses the custom schemes wails:// on macOS and Linux if Vite >= v3.0.0 is used. This makes the dev application consistent in behaviour with the final production application and fixes some long-standing inconsistencies. Changed by @stffabi in https://github.com/wailsapp/wails/pull/2610

Affected the usage of the older version of vite. I added an override to the template to use a version of vite >= 4.0.0 and that seems to work now

**Comment by Stegnerd** [comment]
@sgosiaco  yup can confirm that works for me now as well. Nice work! I am new to quasar and wails so wasn't sure where the problem was! Ty for the cause as well!
